# Generated by Django 3.0.6 on 2022-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_Data', '0002_auto_20220908_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='files',
        ),
        migrations.AddField(
            model_name='users',
            name='file',
            field=models.TextField(default='hello', max_length=300),
        ),
    ]
